-- Dimmo 表情库：成年 Dimmo 与煤球小黑猫的统一状态资产。
-- 后台通过 service role 增删改。当前不提供前台入口或公开读取接口；
-- is_published 暂表示“可调用”，供后续接入聊天、任务或小程序时使用。

create table if not exists public.dimmo_expressions (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  form text not null check (form in ('adult', 'coalball')),
  image_url text,
  storage_path text,
  sprite_sheet_url text,
  sprite_row integer check (sprite_row between 0 and 4),
  sprite_col integer check (sprite_col between 0 and 4),
  alt_text text not null default '',
  tags text[] not null default '{}',
  usage_note text not null default '',
  sort_order integer not null default 0 check (sort_order >= 0),
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dimmo_expression_has_image check (image_url is not null or sprite_sheet_url is not null)
);

create index if not exists dimmo_expressions_public_order_idx
  on public.dimmo_expressions (is_published, sort_order, id);
create index if not exists dimmo_expressions_form_idx
  on public.dimmo_expressions (form, sort_order);

alter table public.dimmo_expressions enable row level security;

drop policy if exists "published dimmo expressions are public" on public.dimmo_expressions;
-- 当前不创建 anon/authenticated 读取策略；service role 后台仍可完整访问。

create or replace function public.touch_dimmo_expression_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_dimmo_expression_updated_at on public.dimmo_expressions;
create trigger touch_dimmo_expression_updated_at
before update on public.dimmo_expressions
for each row execute function public.touch_dimmo_expression_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dimmo-expressions', 'dimmo-expressions', true, 6291456, array['image/png', 'image/webp', 'image/jpeg'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into public.dimmo_expressions
  (name, slug, form, sprite_sheet_url, sprite_row, sprite_col, alt_text, tags, usage_note, sort_order, is_published)
values
  ('会心一笑', 'knowing-smile', 'adult', '/images/dimmo-expression-library-v1.png', 0, 0, 'Dimmo 会心一笑', array['开心','欢迎'], '默认欢迎、轻松回应', 1, true),
  ('煤球登场', 'coalball-arrives', 'coalball', '/images/dimmo-expression-library-v1.png', 0, 1, '煤球小黑猫登场', array['登场','煤球'], '煤球形态首次出现', 2, true),
  ('冲呀', 'lets-go', 'adult', '/images/dimmo-expression-library-v1.png', 0, 2, 'Dimmo 举爪冲呀', array['行动','加油'], '开始任务、快速行动', 3, true),
  ('开心', 'coalball-happy', 'coalball', '/images/dimmo-expression-library-v1.png', 0, 3, '煤球小黑猫开心大笑', array['开心','煤球'], '轻松成功、收到好消息', 4, true),
  ('认真记录', 'take-notes', 'adult', '/images/dimmo-expression-library-v1.png', 0, 4, 'Dimmo 认真记录', array['工作','记录'], '记录留言、保存重点', 5, true),
  ('躲被窝', 'under-blanket', 'adult', '/images/dimmo-expression-library-v1.png', 1, 0, 'Dimmo 躲进被窝', array['休息','可爱'], '休息、暂时离开', 6, true),
  ('认真阅读', 'focused-reading', 'adult', '/images/dimmo-expression-library-v1.png', 1, 1, 'Dimmo 认真阅读', array['阅读','工作'], '阅读资料、理解内容', 7, true),
  ('疑惑', 'coalball-confused', 'coalball', '/images/dimmo-expression-library-v1.png', 1, 2, '煤球小黑猫疑惑', array['疑惑','煤球'], '信息不完整、需要确认', 8, true),
  ('工作中', 'working', 'adult', '/images/dimmo-expression-library-v1.png', 1, 3, 'Dimmo 使用电脑工作', array['工作','加载'], '加载、检索、处理任务', 9, true),
  ('撒花', 'coalball-celebrate', 'coalball', '/images/dimmo-expression-library-v1.png', 1, 4, '煤球小黑猫撒花庆祝', array['庆祝','煤球'], '完成里程碑、成功庆祝', 10, true),
  ('喝杯茶', 'tea-break', 'adult', '/images/dimmo-expression-library-v1.png', 2, 0, 'Dimmo 喝杯茶', array['休息','等待'], '等待、短暂休息', 11, true),
  ('爱心抱抱', 'coalball-hug', 'coalball', '/images/dimmo-expression-library-v1.png', 2, 1, '煤球小黑猫抱住爱心', array['安慰','煤球'], '安慰、感谢、表达关心', 12, true),
  ('思考', 'thinking', 'adult', '/images/dimmo-expression-library-v1.png', 2, 2, 'Dimmo 托腮思考', array['思考','工作'], '分析问题、组织答案', 13, true),
  ('躺平了', 'coalball-flat', 'coalball', '/images/dimmo-expression-library-v1.png', 2, 3, '煤球小黑猫躺平休息', array['疲惫','煤球'], '精力不足、休息状态', 14, true),
  ('冲冲冲', 'delivery-run', 'adult', '/images/dimmo-expression-library-v1.png', 2, 4, 'Dimmo 叼着信封奔跑', array['行动','消息'], '发送消息、投递提醒', 15, true),
  ('探头探脑', 'peek-box', 'adult', '/images/dimmo-expression-library-v1.png', 3, 0, 'Dimmo 从纸箱里探头', array['探头','召回'], '久未操作、从边缘探头', 16, true),
  ('仔细观察', 'inspect', 'adult', '/images/dimmo-expression-library-v1.png', 3, 1, 'Dimmo 用放大镜观察', array['观察','工作'], '核对详情、检查资料', 17, true),
  ('惊', 'coalball-surprised', 'coalball', '/images/dimmo-expression-library-v1.png', 3, 2, '煤球小黑猫惊讶', array['惊讶','煤球'], '出现意外结果或提醒', 18, true),
  ('小憩一下', 'nap', 'adult', '/images/dimmo-expression-library-v1.png', 3, 3, 'Dimmo 蜷在垫子上睡觉', array['睡觉','等待'], '空闲、加载等待、夜间', 19, true),
  ('求安慰', 'coalball-comfort', 'coalball', '/images/dimmo-expression-library-v1.png', 3, 4, '煤球小黑猫眼泪汪汪', array['委屈','煤球'], '失败反馈、需要安慰', 20, true),
  ('任务完成', 'task-complete', 'adult', '/images/dimmo-expression-library-v1.png', 4, 0, 'Dimmo 举起完成清单', array['完成','工作'], '任务完成、清单达成', 21, true),
  ('喵喵喵', 'coalball-meow', 'coalball', '/images/dimmo-expression-library-v1.png', 4, 1, '煤球小黑猫开心喵喵', array['招呼','煤球'], '主动招呼、活泼回应', 22, true),
  ('收到', 'received', 'adult', '/images/dimmo-expression-library-v1.png', 4, 2, 'Dimmo 举旗表示收到', array['确认','工作'], '确认收到消息或指令', 23, true),
  ('酷酷哒', 'coalball-cool', 'coalball', '/images/dimmo-expression-library-v1.png', 4, 3, '煤球小黑猫戴墨镜', array['得意','煤球'], '彩蛋、轻松成就', 24, true),
  ('加油', 'cheer-up', 'adult', '/images/dimmo-expression-library-v1.png', 4, 4, 'Dimmo 举起加油牌', array['加油','鼓励'], '鼓励用户继续完成任务', 25, true)
on conflict (slug) do update set
  name = excluded.name,
  form = excluded.form,
  sprite_sheet_url = excluded.sprite_sheet_url,
  sprite_row = excluded.sprite_row,
  sprite_col = excluded.sprite_col,
  alt_text = excluded.alt_text,
  tags = excluded.tags,
  usage_note = excluded.usage_note,
  sort_order = excluded.sort_order;

comment on table public.dimmo_expressions is 'Dimmo 成年与煤球双形态表情、动作和产品使用场景库';
